"""Publication-ready plot styles."""

PLOT_STYLES = {
    "Thermochimica Acta": {
        "font.family": "serif",
        "font.serif": ["Times New Roman", "DejaVu Serif"],
        "figure.figsize": (7.5, 5.0),
        "axes.labelsize": 12,
        "axes.titlesize": 14,
        "legend.fontsize": 10,
        "xtick.labelsize": 11,
        "ytick.labelsize": 11,
        "axes.grid": True,
        "grid.linestyle": "--",
        "grid.alpha": 0.5,
    },
    "International Journal of Heat": {
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "DejaVu Sans"],
        "figure.figsize": (8.0, 5.5),
        "axes.labelsize": 12,
        "axes.titlesize": 14,
        "legend.fontsize": 10,
        "axes.grid": True,
        "grid.linestyle": "-",
        "grid.alpha": 0.3,
    },
    "Nature": {
        "font.family": "sans-serif",
        "font.sans-serif": ["Helvetica", "Arial"],
        "figure.figsize": (6.5, 4.8),
        "axes.labelsize": 10,
        "axes.titlesize": 12,
        "legend.fontsize": 9,
        "axes.grid": False,
    },
    "Colorblind": {
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial"],
        "figure.figsize": (7.5, 5.0),
        "axes.labelsize": 12,
        "legend.fontsize": 10,
        "axes.grid": True,
        "grid.linestyle": "--",
        "grid.alpha": 0.5,
    },
    "Journal of Energetic Materials": {
        "font.family": "serif",
        "font.serif": ["Times New Roman", "DejaVu Serif"],
        "figure.figsize": (7.0, 5.0),
        "axes.labelsize": 11,
        "axes.titlesize": 13,
        "legend.fontsize": 9,
        "xtick.labelsize": 10,
        "ytick.labelsize": 10,
        "axes.grid": True,
        "grid.linestyle": "-",
        "grid.alpha": 0.4,
        "axes.linewidth": 1.0,
        "xtick.major.width": 1.0,
        "ytick.major.width": 1.0,
    },
    "Energetic Materials Frontiers": {
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "Helvetica"],
        "figure.figsize": (7.5, 5.0),
        "axes.labelsize": 12,
        "axes.titlesize": 14,
        "legend.fontsize": 10,
        "xtick.labelsize": 11,
        "ytick.labelsize": 11,
        "axes.grid": True,
        "grid.linestyle": "--",
        "grid.alpha": 0.3,
        "axes.linewidth": 1.2,
        "xtick.major.width": 1.2,
        "ytick.major.width": 1.2,
    },
    "Journal of Thermal Analysis and Calorimetry": {
        "font.family": "serif",
        "font.serif": ["Times New Roman", "DejaVu Serif"],
        "figure.figsize": (7.0, 5.0),
        "axes.labelsize": 11,
        "axes.titlesize": 13,
        "legend.fontsize": 9,
        "xtick.labelsize": 10,
        "ytick.labelsize": 10,
        "axes.grid": True,
        "grid.linestyle": ":",
        "grid.alpha": 0.5,
        "axes.linewidth": 1.0,
        "xtick.major.width": 1.0,
        "ytick.major.width": 1.0,
    },
    "Propellants, Explosives, Pyrotechnics": {
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "Helvetica"],
        "figure.figsize": (7.0, 5.0),
        "axes.labelsize": 11,
        "axes.titlesize": 13,
        "legend.fontsize": 9,
        "xtick.labelsize": 10,
        "ytick.labelsize": 10,
        "axes.grid": True,
        "grid.linestyle": "-",
        "grid.alpha": 0.25,
        "axes.linewidth": 1.0,
        "xtick.major.width": 1.0,
        "ytick.major.width": 1.0,
        "legend.framealpha": 0.85,
    },
}
